version: '3'
services:
  nginx-php:
    image: romeoz/docker-nginx-php:7.3
    container_name: nginx-php-server
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./docker/nginx-php/conf.d/:/etc/nginx/conf.d
      - ./docker/nginx-php/sites-enabled/:/etc/nginx/sites-enabled
      - ./:/var/www/app/
    tty: true
  mariaDB:
    image: mariadb:10.4
    container_name: mariadb-server
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    tty: true
  redis:
    image: redis:5.0
    container_name: redis-server
    ports:
      - "6379:6379"
    tty: true
